FROM centos:7.4.1708
ARG REPOSITORY=http://10.0.2.15/contrail

RUN yum clean all -y && rm -rf /var/cache/yum
RUN printf "[contrail] \nname = Contrail repo \nbaseurl = $REPOSITORY \nenabled = 1 \ngpgcheck = 0\n" >> /etc/yum.repos.d/contrail.repo \
    && echo "export TERM=xterm" >> ~/.bashrc

# Setup Chrome Repo
COPY google-chrome.repo /etc/yum.repos.d/google-chrome.repo

RUN yum update -y && \
    yum install -y \
      yum-plugin-priorities \
      https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

RUN yum install -y unzip vim tcpdump ant git ipmitool gcc python-devel \
      patch sshpass bzip2 wget sudo python-pip python-netaddr python-lxml \
      python-testresources python-testrepository python-junitxml pexpect \
      python-linecache2 python-xmltodict python-eventlet python-ncclient \
      python-Fabric python-tabulate python-netifaces python-scp python-yaml \
      python-crypto python-urllib3 python-requests python-jinja2 \
      libXpm libXrender gtk2 nss GConf2 google-chrome-stable firefox && \
    yum clean all -y && \
    rm -rf /var/cache/yum

# Install Chrome Driver
RUN wget -c http://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip && \
    unzip chromedriver_linux64.zip && cp ./chromedriver /usr/bin/ && \
    chmod ugo+rx /usr/bin/chromedriver

# pip install python packages
COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
RUN mkdir -p /images

COPY entrypoint.sh /
