- project:
    name: Juniper/contrail-container-builder
    experimental:
      jobs:
        - contrail-vnc-build-package-rhel7-queens
        - contrail-build-containers-rhel7-queens:
            dependencies:
              - contrail-vnc-build-package-rhel7-queens
