ARG OS_VERSION=latest

FROM ubuntu:$OS_VERSION

MAINTAINER Pawel Kopka <pawel.kopka@codilime.com>

RUN apt-get update && \
    apt-get install -y openvpn && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

VOLUME ["/etc/multicloud/openvpn/", "/etc/multicloud/ssl/"]

CMD ["/usr/sbin/openvpn"]

