ARG CONTRAIL_REGISTRY=localhost:5000
ARG CONTRAIL_CONTAINER_TAG=4.1.0.0-6-ubuntu16-newton
FROM ${CONTRAIL_REGISTRY}/contrail-base:${CONTRAIL_CONTAINER_TAG}

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y contrail-openstack-analytics python-sqlalchemy && \
    apt-get clean && \
    rm -rf /var/cache/apt

CMD ["/usr/bin/tail","-f","/dev/null"]
