#ARG CONTRAIL_REGISTRY=localhost:5000
#ARG CONTRAIL_CONTAINER_TAG=4.1.0.0-6-centos7-newton
FROM 10.204.216.66:5000/contrail-base:4.1.0.0-6-centos7-newton

RUN yum install -y pciutils contrail-vrouter-utils contrail-vrouter-dpdk contrail-vrouter-dpdk-init && \
        sudo python-opencontrail-vrouter-netns python-contrail-vrouter-api && \
    yum clean all && \
    rm -rf /var/cache/yum && \
    ldconfig

COPY 10-core-pattern.conf /etc/sysctl.d/
COPY entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]

LABEL net.juniper.contrail=contrail-vrouter-agent-dpdk
LABEL net.juniper.node=agent
