ARG CONTRAIL_REGISTRY=localhost:5000
ARG CONTRAIL_CONTAINER_TAG=4.1.0.0-6-centos7-newton
FROM ${CONTRAIL_REGISTRY}/contrail-base:${CONTRAIL_CONTAINER_TAG}

RUN yum install -y pciutils contrail-vrouter-utils contrail-vrouter-dpdk contrail-vrouter-dpdk-init kmod && \
    yum clean all && \
    rm -rf /var/cache/yum && \
    ldconfig

COPY 10-core-pattern.conf /etc/sysctl.d/
COPY entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]

LABEL net.juniper.contrail=contrail-vrouter-agent-dpdk
LABEL net.juniper.node=agent
