ARG CONTRAIL_VERSION=4.1.0.0-6
ARG CONTRAIL_REGISTRY=localhost:5000
ARG OPENSTACK_VERSION=newton
ARG LINUX_DISTR=ubuntu
FROM ${CONTRAIL_REGISTRY}/contrail-base:${CONTRAIL_VERSION}-${LINUX_DISTR}-${OPENSTACK_VERSION}

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y contrail-config-openstack && \
    apt-get clean && \
    rm -rf /var/cache/apt

CMD ["/usr/bin/tail","-f","/dev/null"]
