ARG CONTRAIL_VERSION=4.1.0.0-6
ARG CONTRAIL_REGISTRY=localhost:5000
ARG OPENSTACK_VERSION=newton
ARG LINUX_DISTR=ubuntu
FROM ${CONTRAIL_REGISTRY}/contrail-base:${CONTRAIL_VERSION}-${LINUX_DISTR}-${OPENSTACK_VERSION}

RUN apt-get install -y contrail-vrouter contrail-vrouter-utils && \
    apt-get clean && \
    rm -rf /var/cache/apt

COPY entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]

LABEL net.juniper.contrail=vrouter-init-kernel
LABEL net.juniper.node=agent
