# Configs section
# Note: using ".." for ports, because in v1 there is a bug
# which leads to an error
# "..error unmarshaling JSON: json: cannot unmarshal number into Go value of type string.."
# (https://github.com/kubernetes/kubernetes/issues/2763)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env
  namespace: kube-system
data:
  AAA_MODE: {{ AAA_MODE }}
  ANALYTICS_API_VIP: {{ ANALYTICS_API_VIP }}
  ANALYTICS_NODES: {{ ANALYTICS_NODES }}
  ANALYTICSDB_NODES: {{ ANALYTICSDB_NODES }}
  AUTH_MODE: {{ AUTH_MODE }}
  CLOUD_ORCHESTRATOR: {{ CLOUD_ORCHESTRATOR }}
  CONFIG_API_VIP: {{ CONFIG_API_VIP }}
  CONFIG_NODES: {{ CONFIG_NODES }}
  CONFIGDB_NODES: {{ CONFIGDB_NODES }}
  CONTROL_NODES: {{ CONTROL_NODES }}
  CONTROLLER_NODES: {{ CONTROLLER_NODES }}
  KAFKA_NODES: {{ KAFKA_NODES }}
  LOG_LEVEL: {{ LOG_LEVEL }}
  METADATA_PROXY_SECRET: {{ METADATA_PROXY_SECRET }}
  RABBITMQ_NODES: {{ RABBITMQ_NODES }}
  RABBITMQ_NODE_PORT: "{{ RABBITMQ_NODE_PORT }}"
  REDIS_NODES: {{ REDIS_NODES }}
  WEBUI_NODES: {{ WEBUI_NODES }}
  WEBUI_VIP: {{ WEBUI_VIP }}
  ZOOKEEPER_NODES: {{ ZOOKEEPER_NODES }}
  ZOOKEEPER_PORTS: "{{ ZOOKEEPER_PORTS }}"
  SSL_ENABLE: "{{ SSL_ENABLE }}"
  SSL_INSECURE: "{{ SSL_INSECURE }}"
  SERVER_CERTFILE: {{ SERVER_CERTFILE }}
  SERVER_KEYFILE: {{ SERVER_KEYFILE }}
  SERVER_CA_CERTFILE: {{ SERVER_CA_CERTFILE }}
  XMPP_SSL_ENABLE: "{{ XMPP_SSL_ENABLE }}"
  XMPP_SERVER_CERTFILE: {{ XMPP_SERVER_CERTFILE }}
  XMPP_SERVER_KEYFILE: {{ XMPP_SERVER_KEYFILE }}
  XMPP_SERVER_CA_CERTFILE: {{ XMPP_SERVER_CA_CERTFILE }}
  INTROSPECT_SSL_ENABLE: "{{ INTROSPECT_SSL_ENABLE }}"
  INTROSPECT_SSL_INSECURE: "{{ INTROSPECT_SSL_INSECURE }}"
  INTROSPECT_CERTFILE: {{ INTROSPECT_CERTFILE }}
  INTROSPECT_KEYFILE: {{ INTROSPECT_KEYFILE }}
  INTROSPECT_CA_CERTFILE: {{ INTROSPECT_CA_CERTFILE }}
  SANDESH_SSL_ENABLE: "{{ SANDESH_SSL_ENABLE }}"
  SANDESH_CERTFILE: {{ SANDESH_CERTFILE }}
  SANDESH_KEYFILE: {{ SANDESH_KEYFILE }}
  SANDESH_CA_CERTFILE: {{ SANDESH_CA_CERTFILE }}
  KEYSTONE_AUTH_PROTO: "{{ KEYSTONE_AUTH_PROTO }}"
  KEYSTONE_AUTH_INSECURE: "{{ KEYSTONE_AUTH_INSECURE }}"
  KEYSTONE_AUTH_CERTFILE: {{ KEYSTONE_AUTH_CERTFILE }}
  KEYSTONE_AUTH_KEYFILE: {{  KEYSTONE_AUTH_KEYFILE}}
  KEYSTONE_AUTH_CA_CERTFILE: {{ KEYSTONE_AUTH_CA_CERTFILE }}
  RABBITMQ_USE_SSL: "{{ RABBITMQ_USE_SSL }}"
  RABBITMQ_CLIENT_SSL_CERTFILE: {{ RABBITMQ_CLIENT_SSL_CERTFILE }}
  RABBITMQ_CLIENT_SSL_KEYFILE: {{ RABBITMQ_CLIENT_SSL_KEYFILE }}
  RABBITMQ_CLIENT_SSL_CACERTFILE: {{ RABBITMQ_CLIENT_SSL_CACERTFILE }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configzkenv
  namespace: kube-system
data:
  ZOOKEEPER_PORT: "{{ ZOOKEEPER_PORT }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: analyticszkenv
  namespace: kube-system
data:
  ZOOKEEPER_PORT: "{{ ZOOKEEPER_ANALYTICS_PORT }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nodemgr-config
  namespace: kube-system
data:
  DOCKER_HOST: "unix://mnt/docker.sock"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-analyticsdb-config
  namespace: kube-system
data:
  CASSANDRA_SEEDS: {{ ANALYTICSDB_NODES }}
  CASSANDRA_CLUSTER_NAME: Contrail
  CASSANDRA_START_RPC: "true"
  CASSANDRA_LISTEN_ADDRESS: auto
  CASSANDRA_PORT: "9160"
  CASSANDRA_CQL_PORT: "9042"
  CASSANDRA_SSL_STORAGE_PORT: "7001"
  CASSANDRA_STORAGE_PORT: "7000"
  CASSANDRA_JMX_LOCAL_PORT: "7200"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-configdb-config
  namespace: kube-system
data:
  CASSANDRA_SEEDS: {{ CONFIGDB_NODES }}
  CASSANDRA_CLUSTER_NAME: ContrailConfigDB
  CASSANDRA_START_RPC: "true"
  CASSANDRA_LISTEN_ADDRESS: auto
  CASSANDRA_PORT: "9161"
  CASSANDRA_CQL_PORT: "9041"
  CASSANDRA_SSL_STORAGE_PORT: "7011"
  CASSANDRA_STORAGE_PORT: "7010"
  CASSANDRA_JMX_LOCAL_PORT: "7201"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: kube-system
data:
  RABBITMQ_ERLANG_COOKIE: "47EFF3BB-4786-46E0-A5BB-58455B3C2CB4"
  RABBITMQ_SSL_CERTFILE: {{ RABBITMQ_SSL_CERTFILE }}
  RABBITMQ_SSL_KEYFILE: {{ RABBITMQ_SSL_KEYFILE }}
  RABBITMQ_SSL_CACERTFILE: {{ RABBITMQ_SSL_CACERTFILE }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-manager-config
  namespace: kube-system
data:
  KUBERNETES_API_SERVER: {{ KUBERNETES_API_SERVER }}
  K8S_TOKEN_FILE: "/tmp/serviceaccount/token"
# Containers section
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-kube-manager
  namespace: kube-system
  labels:
    app: contrail-kube-manager
spec:
  template:
    metadata:
      labels:
        app: contrail-kube-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: Exists
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      automountServiceAccountToken: false
      hostNetwork: true
      containers:
      - name: contrail-kube-manager
        image: "{{CONTRAIL_REGISTRY}}/contrail-kubernetes-kube-manager:{{CONTRAIL_CONTAINER_TAG}}"
        imagePullPolicy: ""
        envFrom:
        - configMapRef:
            name: env
        - configMapRef:
            name: configzkenv
        - configMapRef:
            name: kube-manager-config
        volumeMounts:
        - mountPath: /var/log/contrail
          name: kube-manager-logs
        - mountPath: /tmp/serviceaccount
          name: pod-secret
      volumes:
      - name: kube-manager-logs
        hostPath:
          path: /var/log/contrail/kube-manager
      - name: pod-secret
        secret:
          secretName: contrail-kube-manager-token
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-agent
  namespace: kube-system
  labels:
    app: contrail-agent
spec:
  template:
    metadata:
      labels:
        app: contrail-agent
    spec:
      #Disable affinity for single node setup
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.opencontrail.org/controller"
                operator: NotIn
                values:
                - "true"
      #Enable tolerations for single node setup
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      automountServiceAccountToken: false
      hostNetwork: true
      initContainers:
      - name: contrail-vrouter-kernel-init
        image: "{{CONTRAIL_REGISTRY}}/contrail-vrouter-kernel-init:{{CONTRAIL_CONTAINER_TAG}}"
        imagePullPolicy: ""
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: env
        - configMapRef:
            name: configzkenv
        volumeMounts:
        - mountPath: /usr/src
          name: usr-src
        - mountPath: /lib/modules
          name: lib-modules
      - name: contrail-kubernetes-cni-init
        image: "{{CONTRAIL_REGISTRY}}/contrail-kubernetes-cni-init:{{CONTRAIL_CONTAINER_TAG}}"
        imagePullPolicy: ""
        envFrom:
        - configMapRef:
            name: env
        - configMapRef:
            name: configzkenv
        volumeMounts:
        - mountPath: /var/lib/contrail
          name: var-lib-contrail
        - mountPath: /host/etc_cni
          name: etc-cni
        - mountPath: /host/opt_cni_bin
          name: opt-cni-bin
        - mountPath: /host/log_cni
          name: var-log-contrail-cni
        - mountPath: /var/log/contrail
          name: agent-logs
      containers:
      - name: contrail-vrouter-agent
        image: "{{CONTRAIL_REGISTRY}}/contrail-vrouter-agent:{{CONTRAIL_CONTAINER_TAG}}"
        imagePullPolicy: ""
        # TODO: Priveleged mode is requied because w/o it the device /dev/net/tun
        # is not present in the container. The mounting it into container
        # doesnt help because of permissions are not enough syscalls,
        # e.g. https://github.com/Juniper/contrail-controller/blob/master/src/vnsw/agent/contrail/linux/pkt0_interface.cc: 48.
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: env
        - configMapRef:
            name: configzkenv
        volumeMounts:
        - mountPath: /dev
          name: dev
        - mountPath: /etc/sysconfig/network-scripts
          name: network-scripts
        - mountPath: /var/log/contrail
          name: agent-logs
        - mountPath: /usr/src
          name: usr-src
        - mountPath: /lib/modules
          name: lib-modules
        - mountPath: /var/lib/contrail
          name: var-lib-contrail
        - mountPath: /var/crashes
          name: var-crashes
        - mountPath: /tmp/serviceaccount
          name: pod-secret
      - name: contrail-agent-nodemgr
        image: "{{CONTRAIL_REGISTRY}}/contrail-nodemgr:{{CONTRAIL_CONTAINER_TAG}}"
        imagePullPolicy: ""
        envFrom:
        - configMapRef:
            name: env
        - configMapRef:
            name: configzkenv
        - configMapRef:
            name: nodemgr-config
        env:
        - name: NODE_TYPE
          value: vrouter
# todo: there is type Socket in new kubernetes, it is possible to use full
# path:
# hostPath:
#   path: /var/run/docker.sock and
#   type: Socket
        volumeMounts:
        - mountPath: /var/log/contrail
          name: agent-logs
        - mountPath: /mnt
          name: docker-unix-socket
      volumes:
      - name: dev
        hostPath:
          path: /dev
      - name: network-scripts
        hostPath:
          path: /etc/sysconfig/network-scripts
      - name: docker-unix-socket
        hostPath:
          path: /var/run
      - name: pod-secret
        secret:
          secretName: contrail-kube-manager-token
      - name: usr-src
        hostPath:
          path: /usr/src
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: var-lib-contrail
        hostPath:
          path: /var/lib/contrail
      - name: var-crashes
        hostPath:
          path: /var/contrail/crashes
      - name: etc-cni
        hostPath:
          path: /etc/cni
      - name: opt-cni-bin
        hostPath:
          path: /opt/cni/bin
      - name: var-log-contrail-cni
        hostPath:
          path: /var/log/contrail/cni
      - name: agent-logs
        hostPath:
          path: /var/log/contrail/agent

# Meta information section
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: contrail-kube-manager
  namespace: kube-system
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contrail-kube-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: contrail-kube-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contrail-kube-manager
subjects:
- kind: ServiceAccount
  name: contrail-kube-manager
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: contrail-kube-manager-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: contrail-kube-manager
type: kubernetes.io/service-account-token


