# This is the general base for all: non-contrail specfic like external and for contrail specific

ARG LINUX_DISTR=ubuntu
ARG LINUX_DISTR_VER=16.04
FROM $LINUX_DISTR:$LINUX_DISTR_VER

# this copy should be before apt-get install
COPY *.list /etc/apt/sources.list.d/

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y software-properties-common iproute2 less && \
    apt-get autoremove

COPY *.sh /

CMD ["/usr/bin/tail","-f","/dev/null"]
