ARG CONTRAIL_REGISTRY=localhost:5000
ARG CONTRAIL_CONTAINER_TAG=4.1.0.0-6-ubuntu16-newton
FROM ${CONTRAIL_REGISTRY}/contrail-base:${CONTRAIL_CONTAINER_TAG}

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y contrail-heat python-contrail && \
    apt-get autoremove && \
    apt-get clean && \
    rm -rf /var/cache/apt

COPY *.sh /

ENTRYPOINT ["/entrypoint.sh"]
