ARG CONTRAIL_REGISTRY=localhost:5000
FROM ${CONTRAIL_REGISTRY}/contrail-test-base:latest

ARG OPENSTACK_VERSION=newton
ARG OPENSTACK_SUBVERSION=5

RUN yum install -y \
      https://repos.fedorapeople.org/repos/openstack/openstack-$OPENSTACK_VERSION/rdo-release-$OPENSTACK_VERSION-$OPENSTACK_SUBVERSION.noarch.rpm && \
    yum install -y \
      python-ceilometerclient python-cinderclient python-barbicanclient \
      python-glanceclient python-heatclient python-novaclient \
      python-selenium python-kubernetes && \
    yum clean all -y && rm -rf /var/cache/yum

LABEL net.juniper.contrail=test
LABEL net.juniper.node=test
